---
- name: Self-heal NGINX container
  hosts: local
  gather_facts: false
  collections:
    - community.docker

  tasks:
    - name: Ensure demo-nginx is running (create/start if needed)
      community.docker.docker_container:
        name: demo-nginx
        image: nginx:alpine
        state: started
        restart_policy: always
        published_ports:
          - "8080:80"

    - name: Log action
      debug:
        msg: "Ensured demo-nginx is up (self-heal executed)."
